-- Update teacher emails to use first two names + @glorious.com format
UPDATE public.teachers SET email = 'namulindwasylvia@glorious.com' WHERE name = 'Namulindwa Sylvia';
UPDATE public.teachers SET email = 'nelvinangella@glorious.com' WHERE name = 'Nelvin Angella';
UPDATE public.teachers SET email = 'agnesnakiwala@glorious.com' WHERE name = 'Agnes Nakiwala';
UPDATE public.teachers SET email = 'ajunamathias@glorious.com' WHERE name = 'Ajuna Mathias';
UPDATE public.teachers SET email = 'ndawulasam@glorious.com' WHERE name = 'Ndawula Sam';
UPDATE public.teachers SET email = 'nakanjakoteddy@glorious.com' WHERE name = 'Nakanjako Teddy';
UPDATE public.teachers SET email = 'atwiineedmond@glorious.com' WHERE name = 'Atwiine Edmond';
UPDATE public.teachers SET email = 'mirumumansur@glorious.com' WHERE name = 'Mirumu Mansur';
UPDATE public.teachers SET email = 'niyokindibenoit@glorious.com' WHERE name = 'Niyokindi Benoit';
UPDATE public.teachers SET email = 'kusaasirabarbra@glorious.com' WHERE name = 'Kusaasira Barbra';
UPDATE public.teachers SET email = 'akullomonica@glorious.com' WHERE name = 'Akullo Monica';
UPDATE public.teachers SET email = 'nantongofatuma@glorious.com' WHERE name = 'Nantongo Fatuma';
UPDATE public.teachers SET email = 'akellosarrah@glorious.com' WHERE name = 'Akello Sarah';
UPDATE public.teachers SET email = 'bukenyaisaac@glorious.com' WHERE name = 'Bukenya Isaac';
UPDATE public.teachers SET email = 'mujunigraciano@glorious.com' WHERE name = 'Mujuni Graciano';
UPDATE public.teachers SET email = 'nansubugagloria@glorious.com' WHERE name = 'Nansubuga Gloria';
UPDATE public.teachers SET email = 'lwangavicent@glorious.com' WHERE name = 'Lwanga Vicent';
UPDATE public.teachers SET email = 'wathumherbert@glorious.com' WHERE name = 'Wathum Herbert';
UPDATE public.teachers SET email = 'geraldbenjamin@glorious.com' WHERE name = 'Gerald Benjamin Epodoi';
UPDATE public.teachers SET email = 'nazziwasharon@glorious.com' WHERE name = 'Nazzziwa Sharon';
UPDATE public.teachers SET email = 'nabisubibrenda@glorious.com' WHERE name = 'Nabisubi Brenda';
UPDATE public.teachers SET email = 'namulrimartha@glorious.com' WHERE name = 'Namuli Martha';
UPDATE public.teachers SET email = 'nakatofaridah@glorious.com' WHERE name = 'Nakato Faridah';
UPDATE public.teachers SET email = 'ssemukasalawrence@glorious.com' WHERE name = 'Ssemukasa Lawrence';
UPDATE public.teachers SET email = 'abitegerasylivia@glorious.com' WHERE name = 'Abitegera Sylivia';
UPDATE public.teachers SET email = 'asiojoyce@glorious.com' WHERE name = 'Asio Joyce Mary';
UPDATE public.teachers SET email = 'karunigiolivia@glorious.com' WHERE name = 'Karungi Olivia';
UPDATE public.teachers SET email = 'bongomingabriel@glorious.com' WHERE name = 'Bongomin Gabriel';
UPDATE public.teachers SET email = 'mosesturyomurugyendo@glorious.com' WHERE name = 'Moses Turyomurugyendo';
UPDATE public.teachers SET email = 'hakimlukwago@glorious.com' WHERE name = 'Hakim Lukwago';
UPDATE public.teachers SET email = 'alphajohn@glorious.com' WHERE name = 'Alpha John';
UPDATE public.teachers SET email = 'noelynamuju@glorious.com' WHERE name = 'Noelyn Namuju';
UPDATE public.teachers SET email = 'taremwafravia@glorious.com' WHERE name = 'Taremwa Fravia';