// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qczghrgdwfjhobrjnfdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjemdocmdkd2ZqaG9icmpuZmR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NDk4NTksImV4cCI6MjA3NzIyNTg1OX0.e4PxGPGn2ToNyHZIbdQHypwtyRrs3qUdCVrN39WKq7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});