// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Using the existing backend to avoid downtime while Cloud is being set up
const SUPABASE_URL = "https://xeohebxwwjdjfehdrxlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhlb2hlYnh3d2pkamZlaGRyeGx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNDc1NDcsImV4cCI6MjA3NDcyMzU0N30.HMvd7KMvsQfbvS0aGIjl84bj8w_tj1e04CAI8xGDYIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});